# mbuckler/tf-faster-rcnn-deps
#
# Dockerfile to hold dependencies for the Tensorflow implmentation
# of Faster RCNN

FROM python:3.6-slim

SHELL ["/bin/bash", "-c"]

WORKDIR /home/zyb/myProject/face_recognition

# 更换镜像源，加速
#COPY ./configfile/sources.list /etc/apt/sources.list

# Get required packages
RUN apt-get update -qq

# Get required packages
RUN apt-get install -y --no-install-recommends vim \
                  libjpeg-dev \
                  libfreetype6 \
                  libfreetype6-dev \
                  zlib1g-dev \
                  cmake \
                  wget \
                  cython \
                  git \
                  openssl \
                  libssl-dev \
                  libsm6 \
                  libglib2.0-dev \
                  libxrender1 && \
  python -V


RUN pip3 install pip -U -i https://mirrors.aliyun.com/pypi/simple \
&& pip -V \
&& pip config set global.index-url https://mirrors.aliyun.com/pypi/simple

# COPY pip安装包
COPY ./configfile/requirements-cpu.txt ./configfile/requirements.txt

# pip 安装
RUN pip install -r ./configfile/requirements.txt

# 补充
RUN apt-get install libxext-dev -y


# COPY整个工程到docker中
COPY datasets/datasets.tar.gz ./datasets/datasets.tar.gz
COPY tf-faster-rcnn.tar.gz ./tf-faster-rcnn.tar.gz

# COPY命令到docker中
COPY ./configfile/test-cpu.sh ./tf-faster-rcnn/tools/test.sh


#配置环境变量
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:/usr/local/cuda/lib64
ENV CUDA_HOME /usr/local/cuda
ENV PYTHONPATH $PYTHONPATH:/root/coco/PythonAPI
#设置工作目录
WORKDIR /home/zyb/myProject/face_recognition/tf-faster-rcnn/tools

#docker创建
#sudo docker build -t zhangyanbo2007/face-detector-cpu:dev1 -f configfile/Dockerfile-cpu .

#docker镜像存储
sudo docker save zhangyanbo2007/face-detector-cpu:dev1  -o  ./images/face-detector-cpu.tar
sudo chown -R zyb:zyb ./images/face-detector-cpu.tar

#docker镜像分卷存储（2g）
sudo split face-detector-cpu.tar -b 2G  -d -a 2 face-detector-cpu.tar

#docker镜像解压
sudo docker load -i ./images/face-detector-cpu.tar

#docker镜像上传
sudo docker push zhangyanbo2007/face-detector-cpu:dev1

#docker镜像下载
sudo docker pull zhangyanbo2007/face-detector-cpu:dev1

#docker执行
#sudo docker run -v /home/zyb/myProject/face_recognition/test_image:/home/zyb/myProject/face_recognition/tf-faster-rcnn/tools/test_image -it zhangyanbo2007/face-detector-cpu:dev1 sh -c "/bin/bash test.sh"